# Generated by Django 3.1.7 on 2021-05-04 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('colour', models.CharField(choices=[('b', 'blue'), ('r', 'red'), ('g', 'green'), ('y', 'yellow'), ('o', 'orange'), ('s', 'black'), ('n', 'brown'), ('w', 'white')], default='s', max_length=1)),
                ('car_number_plate', models.CharField(default=None, max_length=7, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Car_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.car')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_parking', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(2020, 12, 31, 12, 0))),
                ('end_datetime', models.DateTimeField(default=datetime.datetime(2020, 12, 31, 13, 0))),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.car')),
                ('carpark', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.carpark')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
