# Generated by Django 3.1.4 on 2021-01-24 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_data',
            name='carpark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carpark'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='carpark',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.carpark'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
