# Generated by Django 3.1.7 on 2021-02-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210128_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colour',
            field=models.CharField(choices=[('b', 'blue'), ('r', 'red'), ('g', 'green'), ('y', 'yellow'), ('o', 'orange'), ('s', 'black'), ('n', 'brown'), ('w', 'white')], default='s', max_length=1),
        ),
    ]
