# Generated by Django 3.1.7 on 2021-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210227_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number_plate',
            field=models.CharField(default=None, max_length=7, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Booking_data',
        ),
    ]
