# Generated by Django 3.1.4 on 2021-01-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_places', models.SmallIntegerField()),
                ('occupied_places', models.SmallIntegerField()),
                ('booked_places', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Live_Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('car_number_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.car')),
                ('carpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carpark')),
            ],
        ),
    ]
