# Generated by Django 3.1.7 on 2021-04-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210227_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='live_feed',
            old_name='time_stamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='carpark',
            name='booked_places',
        ),
        migrations.RemoveField(
            model_name='carpark',
            name='occupied_places',
        ),
        migrations.AlterField(
            model_name='live_feed',
            name='car_number_plate',
            field=models.CharField(default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='live_feed',
            name='carpark',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Carpark_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_booking', models.BooleanField()),
                ('data', models.JSONField(default={'00:00:00': 0, '00:15:00': 0, '00:30:00': 0, '00:45:00': 0, '01:00:00': 0, '01:15:00': 0, '01:30:00': 0, '01:45:00': 0, '02:00:00': 0, '02:15:00': 0, '02:30:00': 0, '02:45:00': 0, '03:00:00': 0, '03:15:00': 0, '03:30:00': 0, '03:45:00': 0, '04:00:00': 0, '04:15:00': 0, '04:30:00': 0, '04:45:00': 0, '05:00:00': 0, '05:15:00': 0, '05:30:00': 0, '05:45:00': 0, '06:00:00': 0, '06:15:00': 0, '06:30:00': 0, '06:45:00': 0, '07:00:00': 0, '07:15:00': 0, '07:30:00': 0, '07:45:00': 0, '08:00:00': 0, '08:15:00': 0, '08:30:00': 0, '08:45:00': 0, '09:00:00': 0, '09:15:00': 0, '09:30:00': 0, '09:45:00': 0, '10:00:00': 0, '10:15:00': 0, '10:30:00': 0, '10:45:00': 0, '11:00:00': 0, '11:15:00': 0, '11:30:00': 0, '11:45:00': 0, '12:00:00': 0, '12:15:00': 0, '12:30:00': 0, '12:45:00': 0, '13:00:00': 0, '13:15:00': 0, '13:30:00': 0, '13:45:00': 0, '14:00:00': 0, '14:15:00': 0, '14:30:00': 0, '14:45:00': 0, '15:00:00': 0, '15:15:00': 0, '15:30:00': 0, '15:45:00': 0, '16:00:00': 0, '16:15:00': 0, '16:30:00': 0, '16:45:00': 0, '17:00:00': 0, '17:15:00': 0, '17:30:00': 0, '17:45:00': 0, '18:00:00': 0, '18:15:00': 0, '18:30:00': 0, '18:45:00': 0, '19:00:00': 0, '19:15:00': 0, '19:30:00': 0, '19:45:00': 0, '20:00:00': 0, '20:15:00': 0, '20:30:00': 0, '20:45:00': 0, '21:00:00': 0, '21:15:00': 0, '21:30:00': 0, '21:45:00': 0, '22:00:00': 0, '22:15:00': 0, '22:30:00': 0, '22:45:00': 0, '23:00:00': 0, '23:15:00': 0, '23:30:00': 0, '23:45:00': 0})),
                ('carpark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.carpark')),
            ],
        ),
    ]
