# Generated by Django 3.1.8 on 2021-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210417_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpark',
            name='id',
        ),
        migrations.AddField(
            model_name='carpark',
            name='geometry',
            field=models.JSONField(default={'coordinates': [52.379084, -1.567667], 'type': 'point'}),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
